version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: secure_vault_db
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-gr7_acess}'
      MYSQL_USER: '${DB_USERNAME:-dev}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-dev@4295}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-dev@4295}'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - secure_vault_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secure_vault_backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    networks:
      - secure_vault_network

  webserver:
    image: nginx:alpine
    container_name: secure_vault_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - secure_vault_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: secure_vault_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - secure_vault_network

networks:
  secure_vault_network:
    driver: bridge

volumes:
  db_data:
